ALTER TABLE CUSTOMER ADD  CONSTRAINT FK_CUS_BRANCH_ID FOREIGN KEY(BRANCH_ID) REFERENCES fitness_branch(B_id) ON DELETE SET NULL;

ALTER TABLE CUSTOMER ADD  CONSTRAINT FK_CUS_BATCH_ID FOREIGN KEY(CBATCH_ID) REFERENCES BATCHES(BATCH_id) ON DELETE SET NULL;

ALTER TABLE FITNESS_BRANCH ADD CONSTRAINT FK_BRANCH_MSSN FOREIGN KEY(FMANAGER_SSN) REFERENCES MANAGER(MANAGER_SSN) ON DELETE SET NULL;

ALTER TABLE BATCHES ADD CONSTRAINT FK_BATCH_BID FOREIGN KEY(BRANCH_ID) REFERENCES fitness_branch(B_id) ON DELETE CASCADE;

ALTER TABLE MANAGER ADD CONSTRAINT FK_MANAGER_SSN FOREIGN KEY(MANAGER_SSN) REFERENCES EMPLOYEE(EMP_SSN) ON DELETE CASCADE;



ALTER TABLE MANAGER
ADD CONSTRAINT check_salary
CHECK (monthly_salary > 0);

ALTER TABLE TRAINER
ADD CONSTRAINT check_salary
CHECK (hourly_salary > 0);

ALTER TABLE TRAINER
ADD CONSTRAINT check_trainer_ssn
CHECK (t_ssn BETWEEN '400000' and '500000');

  